const router = require('express').Router();
const { requireAuth } = require('../middleware/auth');
const { aiGenerationLimiter } = require('../middleware/rateLimiters');
const c = require('../controllers/aiCustomerSupportController');
router.get('/stats', requireAuth, c.getStats);
router.get('/categories', requireAuth, c.getCategories);
router.get('/', requireAuth, c.listFaqs);
const { bulkDeleteHandler } = require('../utils/bulkDelete');
const { sendCsv, autoColumns } = require('../utils/csv');
const db = require('../db');
router.post('/bulk-delete', requireAuth, bulkDeleteHandler('support_faqs'));
router.get('/export', requireAuth, async (req, res) => { const { rows } = await db.query('SELECT id, question, category, created_at FROM support_faqs WHERE org_id = $1 ORDER BY created_at DESC', [req.user.orgId]); sendCsv(res, 'ai_support_faqs.csv', rows, autoColumns(rows)); });
router.post('/generate', requireAuth, aiGenerationLimiter, c.generateAnswer);
router.post('/', requireAuth, c.createFaq);
router.put('/:id', requireAuth, c.updateFaq);
router.delete('/:id', requireAuth, c.deleteFaq);
router.post('/:id/helpful', requireAuth, c.markHelpful);
module.exports = router;
