const router = require('express').Router();
const { requireAuth } = require('../middleware/auth');
const { aiGenerationLimiter } = require('../middleware/rateLimiters');
const c = require('../controllers/aiDocumentsController');
router.get('/stats', requireAuth, c.getStats);
router.get('/', requireAuth, c.listDocuments);
const { bulkDeleteHandler } = require('../utils/bulkDelete');
const { sendCsv, autoColumns } = require('../utils/csv');
const db = require('../db');
router.post('/bulk-delete', requireAuth, bulkDeleteHandler('ai_documents'));
router.get('/export', requireAuth, async (req, res) => { const { rows } = await db.query('SELECT id, title, doc_type, created_at FROM ai_documents WHERE org_id = $1 ORDER BY created_at DESC', [req.user.orgId]); sendCsv(res, 'ai_documents.csv', rows, autoColumns(rows)); });
router.get('/:id', requireAuth, c.getDocument);
router.post('/', requireAuth, c.createDocument);
router.put('/:id', requireAuth, c.updateDocument);
router.delete('/:id', requireAuth, c.deleteDocument);
router.post('/generate', requireAuth, aiGenerationLimiter, c.generateContent);
module.exports = router;
