const router = require('express').Router();
const { requireAuth } = require('../middleware/auth');
const { aiGenerationLimiter } = require('../middleware/rateLimiters');
const c = require('../controllers/aiKnowledgeBaseController');
router.get('/stats', requireAuth, c.getStats);
router.get('/categories', requireAuth, c.getCategories);
router.get('/', requireAuth, c.listArticles);
const { bulkDeleteHandler } = require('../utils/bulkDelete');
const { sendCsv, autoColumns } = require('../utils/csv');
const db = require('../db');
router.post('/bulk-delete', requireAuth, bulkDeleteHandler('ai_knowledge_articles'));
router.get('/export', requireAuth, async (req, res) => { const { rows } = await db.query('SELECT id, title, category, created_at FROM ai_knowledge_articles WHERE org_id = $1 ORDER BY created_at DESC', [req.user.orgId]); sendCsv(res, 'ai_kb_articles.csv', rows, autoColumns(rows)); });
router.get('/:id', requireAuth, c.getArticle);
router.post('/generate', requireAuth, aiGenerationLimiter, c.generateArticle);
router.post('/', requireAuth, c.createArticle);
router.put('/:id', requireAuth, c.updateArticle);
router.delete('/:id', requireAuth, c.deleteArticle);
router.post('/:id/helpful', requireAuth, c.markHelpful);
module.exports = router;
