const router = require('express').Router();
const { requireAuth } = require('../middleware/auth');
const c = require('../controllers/aiKnowledgeBaseController');
router.get('/stats', requireAuth, c.getStats);
router.get('/categories', requireAuth, c.getCategories);
router.get('/', requireAuth, c.listArticles);
router.get('/:id', requireAuth, c.getArticle);
router.post('/', requireAuth, c.createArticle);
router.put('/:id', requireAuth, c.updateArticle);
router.delete('/:id', requireAuth, c.deleteArticle);
router.post('/:id/helpful', requireAuth, c.markHelpful);
module.exports = router;
