const router = require('express').Router();
const { requireAuth } = require('../middleware/auth');
const { aiGenerationLimiter } = require('../middleware/rateLimiters');
const c = require('../controllers/aiTranslatorController');
router.get('/stats', requireAuth, c.getStats);
router.get('/history', requireAuth, c.listHistory);
router.post('/translate', requireAuth, aiGenerationLimiter, c.translate);
router.delete('/history/:id', requireAuth, c.deleteHistory);
const { bulkDeleteHandler } = require('../utils/bulkDelete');
const { sendCsv, autoColumns } = require('../utils/csv');
const db = require('../db');
router.post('/bulk-delete', requireAuth, bulkDeleteHandler('translation_history'));
router.get('/export', requireAuth, async (req, res) => { const { rows } = await db.query('SELECT id, source_text, source_lang, target_lang, created_at FROM translation_history WHERE org_id = $1 ORDER BY created_at DESC', [req.user.orgId]); sendCsv(res, 'translations.csv', rows, autoColumns(rows)); });
module.exports = router;
