const { Router } = require('express');
const { requireAuth } = require('../middleware/auth');
const c = require('../controllers/automationController');
const r = Router();
r.use(requireAuth);
r.get('/stats', c.getStats);
r.get('/workflows', c.listWorkflows);
r.post('/workflows', c.createWorkflow);
r.put('/workflows/:id', c.updateWorkflow);
r.delete('/workflows/:id', c.deleteWorkflow);
r.get('/workflows/:workflowId/steps', c.listSteps);
r.post('/workflows/:workflowId/steps', c.createStep);
r.put('/steps/:id', c.updateStep);
r.delete('/steps/:id', c.deleteStep);
r.get('/enrollments', c.listEnrollments);
r.post('/enrollments', c.createEnrollment);
r.put('/enrollments/:id', c.updateEnrollment);
r.delete('/enrollments/:id', c.deleteEnrollment);
r.get('/enrollments/:enrollmentId/runs', c.listStepRuns);
module.exports = r;
