const { Router } = require('express');
const { requireAuth } = require('../middleware/auth');
const c = require('../controllers/certificatesController');
const r = Router();
r.use(requireAuth);
r.get('/stats',  c.getStats);
r.get('/',       c.listCertificates);
r.post('/',      c.createCertificate);
r.put('/:id',    c.updateCertificate);
r.delete('/:id', c.deleteCertificate);
const { bulkDeleteHandler } = require('../utils/bulkDelete');
const { sendCsv, autoColumns } = require('../utils/csv');
const db = require('../db');
r.post('/bulk-delete', bulkDeleteHandler('issued_certificates'));
r.get('/export', async (req, res) => { const { rows } = await db.query('SELECT id, title, recipient_name, created_at FROM issued_certificates WHERE org_id = $1 ORDER BY created_at DESC', [req.user.orgId]); sendCsv(res, 'certificates.csv', rows, autoColumns(rows)); });
module.exports = r;
