const router = require('express').Router();
const { requireAuth } = require('../middleware/auth');
const { aiGenerationLimiter } = require('../middleware/rateLimiters');
const c = require('../controllers/chatbotBuilderController');
router.get('/stats', requireAuth, c.getStats);
router.get('/', requireAuth, c.listFlows);
const { bulkDeleteHandler } = require('../utils/bulkDelete');
const { sendCsv, autoColumns } = require('../utils/csv');
const db = require('../db');
router.post('/bulk-delete', requireAuth, bulkDeleteHandler('chatbot_flows'));
router.get('/export', requireAuth, async (req, res) => { const { rows } = await db.query('SELECT id, name, is_active, created_at FROM chatbot_flows WHERE org_id = $1 ORDER BY created_at DESC', [req.user.orgId]); sendCsv(res, 'chatbot_flows.csv', rows, autoColumns(rows)); });
router.get('/:id', requireAuth, c.getFlow);
router.post('/generate', requireAuth, aiGenerationLimiter, c.generateReply);
router.post('/', requireAuth, c.createFlow);
router.put('/:id', requireAuth, c.updateFlow);
router.delete('/:id', requireAuth, c.deleteFlow);
module.exports = router;
