const { Router } = require('express');
const { requireAuth } = require('../middleware/auth');
const c = require('../controllers/digitalProductsController');
const r = Router();
r.use(requireAuth);
r.get('/stats',              c.getStats);
r.get('/',                   c.listProducts);
r.post('/',                  c.createProduct);
r.put('/:id',                c.updateProduct);
r.delete('/:id',             c.deleteProduct);
r.get('/:productId/sales',   c.listSales);
r.post('/:productId/sales',  c.recordSale);
const { bulkDeleteHandler } = require('../utils/bulkDelete');
const { sendCsv, autoColumns } = require('../utils/csv');
const db = require('../db');
r.post('/bulk-delete', bulkDeleteHandler('digital_products'));
r.get('/export', async (req, res) => { const { rows } = await db.query('SELECT * FROM digital_products WHERE org_id = $1', [req.user.orgId]); sendCsv(res, 'digital_products.csv', rows, autoColumns(rows)); });
module.exports = r;
