const { Router } = require('express');
const { requireAuth } = require('../middleware/auth');
const c = require('../controllers/linkInBioController');
const r = Router();
r.use(requireAuth);
r.get('/stats',               c.getStats);
r.get('/',                    c.listPages);
r.post('/',                   c.createPage);
r.put('/:id',                 c.updatePage);
r.delete('/:id',              c.deletePage);
r.get('/:pageId/links',       c.listLinks);
r.post('/:pageId/links',      c.createLink);
r.put('/links/:id',           c.updateLink);
r.delete('/links/:id',        c.deleteLink);
const { bulkDeleteHandler } = require('../utils/bulkDelete');
const { sendCsv, autoColumns } = require('../utils/csv');
const db = require('../db');
r.post('/bulk-delete', bulkDeleteHandler('link_in_bio_pages'));
r.get('/export', async (req, res) => { const { rows } = await db.query('SELECT * FROM link_in_bio_pages WHERE org_id = $1', [req.user.orgId]); sendCsv(res, 'link_in_bio.csv', rows, autoColumns(rows)); });
module.exports = r;
