const router = require('express').Router();
const { requireAuth } = require('../middleware/auth');
const { aiGenerationLimiter } = require('../middleware/rateLimiters');
const c = require('../controllers/meetingNotesController');
router.get('/stats', requireAuth, c.getStats);
router.get('/', requireAuth, c.listNotes);
const { bulkDeleteHandler } = require('../utils/bulkDelete');
const { sendCsv, autoColumns } = require('../utils/csv');
const db = require('../db');
router.post('/bulk-delete', requireAuth, bulkDeleteHandler('meeting_notes'));
router.get('/export', requireAuth, async (req, res) => { const { rows } = await db.query('SELECT id, title, created_at FROM meeting_notes WHERE org_id = $1 ORDER BY created_at DESC', [req.user.orgId]); sendCsv(res, 'meeting_notes.csv', rows, autoColumns(rows)); });
router.get('/:id', requireAuth, c.getNote);
router.post('/', requireAuth, c.createNote);
router.post('/:id/summarize', requireAuth, aiGenerationLimiter, c.summarize);
router.put('/:id', requireAuth, c.updateNote);
router.delete('/:id', requireAuth, c.deleteNote);
module.exports = router;
