const { Router } = require('express');
const { requireAuth } = require('../middleware/auth');
const c = require('../controllers/ordersController');
const r = Router();
r.use(requireAuth);
r.get('/stats',   c.getStats);
r.get('/',        c.listOrders);
r.get('/export',  c.exportOrders);
r.post('/bulk-delete', c.bulkDeleteOrders);
r.post('/',       c.createOrder);
r.get('/:id',     c.getOrder);
r.put('/:id',     c.updateOrder);
r.delete('/:id',  c.deleteOrder);
module.exports = r;
