const { Router } = require('express');
const { requireAuth } = require('../middleware/auth');
const { requirePayrollAccess } = require('../middleware/hrAuth');
const c = require('../controllers/payrollController');
const r = Router();
r.use(requireAuth, requirePayrollAccess);
r.get('/stats',            c.getStats);
r.get('/',                 c.listRuns);
r.get('/export',           c.exportRuns);
r.post('/bulk-delete',     c.bulkDeleteRuns);
r.post('/',                c.createRun);
r.get('/:id',              c.getRun);
r.put('/:id',              c.updateRun);
r.delete('/:id',           c.deleteRun);
r.post('/:runId/items',    c.addItem);
r.get('/:runId/items/:itemId/payslip', c.getPayslipPdf);
r.delete('/:runId/items/:itemId', c.removeItem);
module.exports = r;
