const { Router } = require('express');
const { requireAuth } = require('../middleware/auth');
const c = require('../controllers/quotationsController');
const r = Router();
r.use(requireAuth);
r.get('/stats',   c.getStats);
r.get('/',        c.listQuotations);
r.get('/:id',     c.getQuotation);
r.post('/',       c.createQuotation);
r.put('/:id',     c.updateQuotation);
r.delete('/:id',  c.deleteQuotation);
const { bulkDeleteHandler } = require('../utils/bulkDelete');
const { sendCsv, autoColumns } = require('../utils/csv');
const db = require('../db');
r.post('/bulk-delete', bulkDeleteHandler('quotations'));
r.get('/export', async (req, res) => { const { rows } = await db.query('SELECT * FROM quotations WHERE org_id = $1', [req.user.orgId]); sendCsv(res, 'quotations.csv', rows, autoColumns(rows)); });
module.exports = r;
