const { Router } = require('express');
const { requireAuth } = require('../middleware/auth');
const c = require('../controllers/whatsappController');
const r = Router();
r.use(requireAuth);
r.get('/stats', c.getStats);
r.get('/contacts', c.listContacts);
r.post('/contacts', c.createContact);
r.put('/contacts/:id', c.updateContact);
r.delete('/contacts/:id', c.deleteContact);
r.get('/templates', c.listTemplates);
r.post('/templates', c.createTemplate);
r.put('/templates/:id', c.updateTemplate);
r.delete('/templates/:id', c.deleteTemplate);
r.get('/broadcasts', c.listBroadcasts);
r.post('/broadcasts', c.createBroadcast);
r.put('/broadcasts/:id', c.updateBroadcast);
r.post('/broadcasts/:id/send', c.sendBroadcast);
r.delete('/broadcasts/:id', c.deleteBroadcast);
module.exports = r;
