/**
 * Auto-CRUD Route Configuration
 * Generates generic CRUD routes for all module slugs that don't have
 * a dedicated controller/route. One route config covers all of them.
 */

const { requireAuth } = require('../../middleware/auth');

/**
 * Auto-CRUD module slugs — these modules have existing DB tables but
 * no dedicated backend controller. The catch-all /:slug handler serves them.
 * Generated by scanning categories.data.js against existing routes.
 */
const AUTO_CRUD_SLUGS = [
  // Marketing
  'pipeline-deals', 'referral-affiliate-analytics-dashboard',
  'landing-page-heat-scroll-analytics', 'customer-segmentation-engine',
  'direct-mail-automation', 'print-fulfillment-for-business-cards-signage',
  'creative-a-b-testing-studio', 'ugc-creator-content-aggregator',
  // AI
  'ai-writer', 'ai-email-assistant', 'ai-proposal-generator', 'ai-blog-generator',
  'ai-image-generator', 'ai-data-enrichment', 'ai-workflow-suggestions',
  'ai-content-repurposing', 'predictive-sales-forecasting', 'churn-prediction',
  'anomaly-detection', 'ai-voice-agent', 'ai-data-analyst', 'ai-sales-call-coach',
  'cross-sell-upsell-recommendation-engine', 'ai-avatar-spokesperson-video-generator',
  'ai-voice-transcription-summarization',
  // Business
  'contract-vendor-management', 'procurement-purchase-orders',
  'multi-location-franchise-management', 'compliance-document-expiry-tracker',
  'shift-scheduling', 'resource-equipment-booking', 'field-service-management',
  'e-signature-contracts', 'internal-wiki-employee-knowledge-base',
  'okr-goal-tracking', 'job-board-external-talent-marketplace',
  'employee-benefits-administration', 'background-check-integration',
  'offboarding-checklist-equipment-asset-return-tracking',
  'employee-wellness-programs', 'dei-reporting-dashboard',
  'return-to-office-desk-booking', 'legal-template-library',
  'trademark-ip-asset-tracker', 'supplier-partner-portal',
  // Education
  'student-portal', 'teacher-portal', 'parent-portal',
  'cohort-live-class-scheduling', 'discussion-forums-per-course',
  'gradebook-analytics-for-parents-admins', 'plagiarism-ai-content-detection',
  // Commerce
  'pos-online-store-inventory-sync', 'multi-vendor-marketplace-payouts',
  'gift-cards', 'wishlist-save-for-later', 'product-reviews-qa',
  'warranty-rma-management', 'loyalty-rewards-program',
  'print-on-demand-integration', 'dropshipping-supplier-integration',
  'shipping-label-printing-carrier-rate-shopping',
  'warranty-registration-portal', 'marketplace-dispute-resolution',
  // Platform Core (already have routes via dedicated handlers)
  // Productivity
  'whiteboard-mind-mapping-tool', 'internal-people-skills-directory',
  'idea-management-suggestion-box', 'multi-timezone-meeting-coordinator',
  // Analytics
  'business-dashboard', 'data-warehouse-connector-export',
  'custom-sql-query-builder', 'scheduled-report-emails-pdfs',
  'cohort-retention-analysis',
  // Trust & Compliance
  'gdpr-ccpa-data-request-center', 'consent-cookie-management',
  'backup-disaster-recovery-console', 'public-status-page',
  'terms-policy-version-tracking', 'customer-facing-audit-trail-export',
  'rtl-language-layout-support', 'esg-sustainability-reporting',
  'multi-language-workspace-ui', 'regional-tax-compliance-packs',
  'localized-payment-methods', 'enterprise-sso-saml',
  'data-residency-selector', 'byok-encryption-key-management',
  'soc2-iso27001-compliance-evidence-dashboard',
  'data-export-portability-suite', 'regulatory-change-monitoring',
  'carbon-footprint-sustainability-tracker-for-operations',
  'localization-translation-management',
  // Support & Success
  'nps-csat-survey-automation', 'customer-health-score', 'sla-management',
  'public-roadmap-feature-request-board', 'live-chat',
  'built-in-voice-video-calling', 'internal-team-messaging',
  // Finance — Advanced
  'multi-entity-accounting', 'budget-planning-forecasting',
  'bill-pay-accounts-payable-automation', 'financing-lending-integration',
  'tax-filing-prep-export', 'fx-currency-hedging-alerts',
  'corporate-card-expense-card-issuing', 'vendor-risk-scorecard',
  'dunning-management', 'usage-based-metered-billing-dashboard',
  'revenue-recognition-automation', 'subscription-pause-skip-self-service',
  'fraud-detection-engine', 'chargeback-dispute-management',
  'identity-verification-kyc', 'sales-tax-nexus-compliance-tracker',
  'international-contractor-payments', 'multi-country-payroll-compliance-packs',
  'cap-table-equity-management', 'board-investor-reporting-portal',
  // Integrations
  'native-integrations-hub', 'public-developer-portal-app-submission-pipeline',
  'sandbox-api-playground', 'oauth-app-directory',
  // Gamification
  'achievement-badge-system', 'leaderboards', 'streaks-habit-tracking',
  'product-tour-onboarding-checklist-builder',
  // Mobile
  'native-mobile-app', 'offline-mode', 'white-label-mobile-app-builder',
  // Media & Content
  'podcast-hosting', 'video-hosting-streaming',
  'interactive-product-demo-builder', 'in-product-guided-tours-editor',
  'print-publishing-workflow',
  // Non-Profit
  'donation-management', 'volunteer-management', 'grant-tracking',
  // Extended Vertical
  'legal-practice-management', 'insurance-policy-claims-management',
  'manufacturing-quality-control', 'travel-hospitality-booking',
  'property-management', 'iot-hardware-device-integration',
  'agriculture-farm-management', 'esports-gaming-community-tools',
  'religious-congregation-management', 'government-rfp-response-management',
];

const AUTO_CRUD_ROUTES = AUTO_CRUD_SLUGS.map(slug => ({
  path: `/api/v1/auto-crud/${slug}`,
  file: 'autoCrud',
  middleware: [requireAuth],
  description: `Auto-CRUD: ${slug}`,
}));

module.exports = { AUTO_CRUD_ROUTES, AUTO_CRUD_SLUGS };
